const NewsAPI = [
    {
        id:1,
        img:'img/1.png',
        title:'Axois',
        title1:'',
        image:'img/close.webp',
        info:'The Supreme Court ruled on Thursday that colleges can  explicitiy consider race when creating their student body, forcing colleges to reimaging long-standing hallmarks of the admissions process. The decision will also likely jeopardize the representation of Black and Latino student on campuses nationwide.',
        add: '' ,
        condition:'',
        data:'Axios-News',
        heart:"150",
        dot:"38",

    },
    {
        id:2,
        img:'img/abc.jpg',
        title:'NBC News ',
        title1:'flipped into Top Stories ',
        image:'img/clg.webp',
        info:'Supreme Court Kills Biden student loan relief plan',
        add: '' ,
        condition:'6 hours ago ',
        data:'NBC News-Lawrence Hurley',
        heart:"1",
        dot:" ",

    },
    {
        id:3,
        img:'img/usa.jpeg',
        title:'USA TODAY',
        title1:'flipped into Top Stories ',
        image:'img/medium.webp',
        info:'Supreme Court backs Christian Worker Who Wnated Sundays off in case that may have wide impact',
        add: '' ,
        condition:'7 hours ago ',
        data:'USA TODAY-John Fritze',
        heart:"47",
        dot:"12",

    },
    {
        id:4,
        img:'img/foxnews.jpeg',
        title:'Zhogfan',
        title1:'flipped into  ',
        image:'img/police.webp',
        info:'Budanov Says Russian FSB Assigned to Eliminate Prigozhim',
        add: '' ,
        condition:'Now ',
        data:'Kyiv Post',
        heart:"76",
        dot:"150",

    },
    {
        id:5,
        img:'img/rs.jpeg',
        title:'Keith Kirby',
        title1:'flipped into News and Black',
        image:'img/student.webp',
        info:'California Ph.D.students research trip to Mexico ends in violents death:"He was in the wrong place"',
        add: '' ,
        condition:'7 hours ago ',
        data:'CBS News',
        heart:"114",
        dot:"1",

    },
    {
        id:6,
        img:'img/man.jpg',
        title:'ABC News',
        title1:'',
        image:'img/souce.webp',
        info:'Judge denies Trumps request to dismiss E.Jeans Carrolls remaining defamation claim',
        add: '' ,
        condition:'21 hours ago ',
        data:'ABC News-Aaron Katersky',
        heart:"71",
        dot:"51",

    },
    {
        id:7,
        img:'img/cnnnn.jpg',
        title:'NPR',
        title1:'',
        image:'img/putin.jpg',
        info:'Here What happened When affirmative action ended at California Public colleges',
        add: '' ,
        condition:'13 hours ago ',
        data:' NPR-Emma Bowman',
        heart:"27",
        dot:"76",

    },
    {
        id:8,
        img:'img/Foxnews.jpeg',
        title:'NBC News',
        title1:'flipped into U.S. News',
        image:'img/boll.jpg',
        info:'Murder Suspect featured on "America"s  Most Wanted arrested after nearly 4 decades on the run',
        add: '' ,
        condition:'6 hours ago ',
        data:'NBC News-The Associated Press',  
        heart:"56",
        dot:"114",
  
    },
    {
        id:9,
        img:'img/cbs.jpeg',
        title:'Rolling Stone',
        title1:'flipped into All News',
        image:'img/pbn.jpg',
        info:'Trump Demanded "My Documents" Back Even After Lawyers Told Him He be Indicated  ',
        add: '' ,
        condition:'1 day  ago ',
        data:'Rolling Stone-Adam Rawnsely',
        heart:"325",
        dot:"71",

    },
    {
        id:10,
        img:'img/aap.png',
        title:'CBS News',
        title1:'',
        image:'img/boss.webp',
        info:'Ukraine top security official says Vladimir Putins Own generals are Working against him ',
        add: '' ,
        condition:'1 day ago ',
        data:'CBS News',
        heart:"177",
        dot:"28",

    },
    {
        id:11,
        img:'img/beast.jpeg',
        title:'ABC News',
        title1:'flipped into News',
        image:'img/car.webp',
        info:'Supreme Courts Strikes down Biden student loan debt forgiveness program',
        add: '' ,
        condition:'2 hours ago ',
        data:'ABC News',
        heart:"3",
        dot:"56",

    },
    {
        id:12,
        img:'img/man1.jpg',
        title:'Kyiv Post',
        title1:'',
        image:'img/hp.webp',
        info:'Fallout From Prigozhin Mutiny-Is a Purge of Russian Generals Underways?',
        add: '' ,
        condition:'1 day ago ',
        data:'Kyiv Post-Steve Brown',
        heart:"137",
        dot:"325",

    },

  
]
export default NewsAPI