const TechnoAPI =[
    {
        id:1,
        img:'img/TT-1.jpeg',
        title:'Kevin Beachus',
        title1:'flipped into Top Stories',
        image:'img/t-1.webp',
        info:'The Supreme Court ruled on Thursday that colleges can  explicitiy consider race when creating their student body, forcing colleges to reimaging long-standing hallmarks of the admissions process. The decision will also likely jeopardize the representation of Black and Latino student on campuses nationwide.',
        add: '' ,
        condition:'1 hours  ago',
        data:'Digital Trends - By Travor Mogg',
        heart:"42",
        

    },
    {
        id:2,
        img:'img/abc.jpg',
        title:'NBC News ',
        title1:'flipped into Top Stories ',
        image:'img/T-2.webp',
        info:'Supreme Court Kills Biden student loan relief plan',
        add: '' ,
        condition:'3 hours ago ',
        data:'NBC News-Lawrence Hurley',
        heart:"11",
        dot:"",
        
    },
    {
        id:3,
        img:'img/usa.jpeg',
        title:'USA TODAY',
        title1:'flipped into Top Stories ',
        image:'img/T-3.webp',
        info:'Supreme Court backs Christian Worker Who Wnated Sundays off in case that may have wide impact',
        add: '' ,
        condition:'Now',
        data:'USA TODAY-John Fritze',
        heart:"11",
        dot:"",
    },
    {
        id:4,
        img:'img/foxnews.jpeg',
        title:'Zhogfan',
        title1:'flipped into  ',
        image:'img/T-4.webp',
        info:'Budanov Says Russian FSB Assigned to Eliminate Prigozhim',
        add: '' ,
        condition:'8 hours ago',
        data:'Kyiv Post',
        heart:"20",
        dot:"",
    },
    {
        id:5,
        img:'img/rs.jpeg',
        title:'Keith Kirby',
        title1:'flipped into News and Black',
        image:'img/T-5.webp',
        info:'California Ph.D.students research trip to Mexico ends in violents death:"He was in the wrong place"',
        add: '' ,
        condition:' 3 hours ago ',
        data:'CBS News',
        heart:"",
        dot:"",
    },
    {
        id:6,
        img:'img/man.jpg',
        title:'ABC News',
        title1:'',
        image:'img/T-6.webp',
        info:'Judge denies Trumps request to dismiss E.Jeans Carrolls remaining defamation claim',
        add: '' ,
        condition:'17 hours ago ',
        data:'ABC News-Aaron Katersky',
        heart:"8",
        dot:"",
    },
    {
        id:7,
        img:'img/cnnnn.jpg',
        title:'NPR',
        title1:'',
        image:'img/T-7.webp',
        info:'Here What happened When affirmative action ended at California Public colleges',
        add: '' ,
        condition:'21 hours ago ',
        data:' NPR-Emma Bowman',
        heart:"11",
        dot:"",
    },
    {
        id:8,
        img:'img/Foxnews.jpeg',
        title:'NBC News',
        title1:'flipped into U.S. News',
        image:'img/T-8.jpg',
        info:'Murder Suspect featured on "America"s  Most Wanted arrested after nearly 4 decades on the run',
        add: '' ,
        condition:'3 hours ago ',
        data:'NBC News-The Associated Press', 
        heart:"16",
        dot:"",   
    },
    {
        id:9,
        img:'img/cbs.jpeg',
        title:'Rolling Stone',
        title1:'flipped into All News',
        image:'img/T-9.webp',
        info:'Trump Demanded "My Documents" Back Even After Lawyers Told Him He be Indicated  ',
        add: '' ,
        condition:'9 day  ago ',
        data:'Rolling Stone-Adam Rawnsely',
        heart:"26",
        dot:"",
    },
    {
        id:10,
        img:'img/aap.png',
        title:'CBS News',
        title1:'',
        image:'img/T-10.webp',
        info:'Ukraine top security official says Vladimir Putins Own generals are Working against him ',
        add: '' ,
        condition:'1 day ago ',
        data:'CBS News',
        heart:"221",
        dot:"",
    },
    {
        id:11,
        img:'img/beast.jpeg',
        title:'ABC News',
        title1:'flipped into News',
        image:'img/T-11.jpg',
        info:'Supreme Courts Strikes down Biden student loan debt forgiveness program',
        add: '' ,
        condition:'1 hours ago ',
        data:'ABC News',
        heart:"27",
        dot:"",
    },
    {
        id:12,
        img:'img/man1.jpg',
        title:'Kyiv Post',
        title1:'',
        image:'img/T-12.webp',
        info:'Fallout From Prigozhin Mutiny-Is a Purge of Russian Generals Underways?',
        add: '' ,
        condition:'21 day ago ',
        data:'Kyiv Post-Steve Brown',
        heart:"15",
        dot:"",
    },



]
export default TechnoAPI
